# Generated by Django 4.2.9 on 2024-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('Kč', 'Kč'), ('€', 'EUR')], default='R', max_length=100),
        ),
    ]
